export const addMerchantForm = [
  {
    label: 'First Name',
    type: 'text',
    fcname: 'firstName',
    show: true,
    default: '',
    required: true,
    validator: [],
  },
  {
    label: 'Middle Name',
    type: 'text',
    fcname: 'middleName',
    show: true,
    default: '',
    required: false,
    validator: [],
  },
  {
    label: 'Last Name',
    type: 'text',
    fcname: 'lastName',
    show: true,
    default: '',
    required: true,
    validator: [],
  },
  {
    label: 'Email',
    type: 'text',
    fcname: 'email',
    show: true,
    default: '',
    required: true,
    validator: [],
  },
  {
    label: 'Mobile Number',
    type: 'number',
    fcname: 'mobileNumber',
    show: true,
    default: '',
    required: true,
    validator: [],
  },
];
